title = "bibelblog."
baseURL = "https://bibelblog.netlify.com"
languageCode = "de-de"
theme = "ananke"
themesDir = "themes/"

MetaDataFormat = "yaml"
DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "assets/favicon.ico"
  description = "die Bibel. für alle. erklärt."
  facebook = ""
  twitter = "https://twitter.com/bibelblog"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/assets/hero-image.jpg"
  recent_posts_number = 4
